# This is a basic workflow that is manually triggered

name: Buil the docker image

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    # Inputs the workflow accepts.
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Build the Docker Image
      runs: echo "Welcome to Github Actions"
      uses: actions/checkout@v1
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "madhumohan" --password-stdin
        docker image build -t madhumohan/flowiseai/nginx-cost-img:latest
		docker push madhumohan/flowiseai/nginx-cost-img:latest
